# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cc5a9562f13d422d61f1b0c80fd5f3eee955154933c1e35bf5bbaace6735fafd217125b772b8a09576dc73022fcbad332b38c067a193ef9f458d989ce5cc643

test:
  secret_key_base: 68da98336f1d6791c5c9bf259bde980c73a4e8236790e0ac8036f430287760d4632eefcf40a2c2a4ec52dad0a1eb8cc1ba4399c2d033378f169672393d46ec32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
